### ISSUE TITLE
LE3063: Only public, static, non-generic methods can be imported!

### ISSUE THREAD

**Issue by ForNeVeR** [impworks/lens#188]
With this restriction, it's almost impossible to import F# function. See my example program below:

```fsharp
open System
open Lens

// little hack from https://stackoverflow.com/a/1575450/2684760
let getMethodInfo (f : 'a -> 'b) = (FSharpFunc.ToConverter f).Method

[<EntryPoint>]
let main argv = 
    let cp = new LensCompiler()
    let foo = fun x -> x + 5
    let res = ref 0
    let mi = getMethodInfo foo
    printfn "isPublic = %A; isStatic = %A, isGeneric = %A" mi.IsPublic mi.IsStatic mi.IsGenericMethod
        // => isPublic = false; isStatic = false, isGeneric = false
    cp.RegisterFunction("foo", mi)
    cp.RegisterProperty("res", fun () -> res.Value, fun v -> res := v)
    let src = "res = foo 10"
    let compiled = cp.Compile src
    
    0
```

I suggest to review that restriction if that's possible for us.

**Comment by impworks** [comment]
Поскольку лямбда является инстанс-методом, ее нужно передавать через `RegisterProperty`. Но есть бага: переданный таким образом делегат нельзя вызвать напрямую из-за ошибки в `InvocationNode`. Это нужно исправить!

**Comment by impworks** [comment]
Сейчас не могу исправить - сначала нужно доделать #187, иначе будут конфликты.
В качестве временного решения, можно использовать явный вызов `Invoke`:

```csharp
Func<int, int> foo = x => x + 5;
cp.RegisterProperty("foo", () => foo);
cp.Run("foo.Invoke 10"); // 15
```

В будущем, можно добавить overload `RegisterFunction(Delegate d)`, чтобы было более наглядно.

**Comment by ForNeVeR** [comment]
`RegisterProperty` подойдёт только для функции без параметров. А что делать, если у меня параметры? Можно, конечно, как-то извернуться на Property (скажем, через несколько пропертей выставлять параметры, а ещё через одну — вызывать функцию), но это кошмар.

**Comment by impworks** [comment]
Бага исправлена, интерфейс компилятора расширен.
