### ISSUE TITLE
Портирование на .NET Core

### ISSUE THREAD

**Issue by impworks** [impworks/lens#194]
Варианты:

* Профиль .NET Standard - в 1.1 вроде бы есть `System.Reflection.Emit`.
* Условная компиляция

Сложности:

* Нельзя сохранить сборку на диск: https://github.com/dotnet/corefx/issues/4491
* Отсутствует `TypeBuilder.CreateType`: [stackoverflow](https://stackoverflow.com/questions/37488458/createtype-missing-from-typebuilder-how-to-port-this)

**Comment by impworks** [comment]
Заодно следует разделить проект на два: `lens` и `lens-demos`. Первый перевести на новый SDK и использовать мультитаргетинг во все поля.

**Comment by impworks** [comment]
Доктор @ForNeVeR, как считаете, в проекте Lens Demos саму библиотеку лучше референсить как nuget-пакет, или git submodule с подключением исходников в проект?

**Comment by ForNeVeR** [comment]
@impworks а нам этого сильно хочется? Мне лично кажется, что разделять на два репозитория будет не очень удобно. При разработке новых фич часто хочется сразу же, прям на месте редактировать демки. Я рекомендую избегать субмодулей, пока это возможно. Ну а с вариантом через нугет разработка демок для новых, ещё не релизнутых фич превратится в цирк с конями (придётся паблишить превью-пакеты в локальный репозиторий или что-то в этом роде).

Если что, `ProjectReference` между проектами на старом и новом SDK (даже в одном солюшене) работает на ура.

**Comment by impworks** [comment]
Запилено в PR #195
